### PR TITLE
Removed deprecated processors 

### PR DESCRIPTION
**Pull request by MarekB01**
https://github.com/BroadleafCommerce/QA/issues/4832

Removed deprecated processors, also updated spring framework to version which other modules use

### CODE REVIEW

**Comment by MarekB01** [comment]
This pr should not be merged now. Looking for usages of removed classes to make more PR's and then it can be merged

**Comment by riteshadhikari17** [comment]
Why did u close this one? We need to remove these. Did u mean to close ur [PR for core](https://github.com/BroadleafCommerce/BroadleafCommerce/pull/2756) and closed this one by mistake?

**Comment by riteshadhikari17** [comment]
@MarekB01 We still need to remove these. Shouldn't u reopen this one Or open new PR?

**Comment by MarekB01** [comment]
Changes from this pr are already merged in 1.4 version

**Comment by riteshadhikari17** [comment]
I don't think so. I still see them in 1.4 branch. https://github.com/BroadleafCommerce/CommonPresentation/tree/develop-1.4.x/src/main/java/org/broadleafcommerce/presentation/dialect

**Comment by MarekB01** [comment]
@riteshadhikari17 Yes, but I just marked them as deprecated. If they have to be removed completely, I'll update this pr adn remove them at all

**Comment by riteshadhikari17** [comment]
Removing deprecated processors is the Task in the QA ticket. This is 6.3 so it's right time remove anything that needs to be removed. I see another PR, please use that to completely remove the deprecated things.

**Comment by MarekB01** [comment]
@riteshadhikari17 check this one - https://github.com/BroadleafCommerce/CommonPresentation/pull/12

**Pull request closed without merging**
